version: "3.9"

services:
  envoy:
    image: grpcweb/envoy
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  # envoy:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   image: grpcweb/envoy
  #   ports:
  #     - "8080:8080"
  #     - "9901:9901"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # restart: always
    # networks:
    #   - server-net

  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=userdb

#   grpc_server:
#     build:
#       context: .
#       dockerfile: grpc.Dockerfile
#     ports:
#       - '6565:6565'
#     networks:
#       - server-net

# networks:
#   server-net:

